# Generated by Django 3.0.3 on 2020-04-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='my_img',
            field=models.ImageField(default='blank', upload_to='images/'),
        ),
    ]
