# Generated by Django 3.0.3 on 2020-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_app', '0004_auto_20200409_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='my_img',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
